# Generated by Django 3.1.1 on 2020-09-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='persons',
            options={'verbose_name': 'Персоны'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.CharField(db_column='Description', max_length=40),
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(db_column='Name', max_length=40),
        ),
    ]
