# Generated by Django 3.1.1 on 2020-09-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_auto_20200926_1949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persons',
            unique_together={('first_name', 'last_name')},
        ),
    ]
