# Generated by Django 3.1.1 on 2020-09-29 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0003_auto_20200927_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['date_time'], 'verbose_name': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='persons',
            options={'ordering': ['date_time'], 'verbose_name': 'Персоны'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['date_time'], 'verbose_name': 'Подписки'},
        ),
        migrations.AddField(
            model_name='groups',
            name='date_time',
            field=models.DateTimeField(db_column='DateTime', default=datetime.datetime(2020, 9, 29, 16, 34, 0, 135608)),
        ),
        migrations.AddField(
            model_name='persons',
            name='date_time',
            field=models.DateTimeField(db_column='DateTime', default=datetime.datetime(2020, 9, 29, 16, 34, 0, 135608)),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='date_time',
            field=models.DateTimeField(db_column='DateTime', default=datetime.datetime(2020, 9, 29, 16, 34, 0, 135608)),
        ),
    ]
